version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres-inventory-service
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-inventory-service:/data/postgres
    restart: unless-stopped